/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as PracticePosRouteImport } from './routes/practice-pos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TerminateRouteImport } from './routes/terminate'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiBetaSignupRouteImport } from './routes/api/beta-signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePosRoute = PracticePosRouteImport.update({
  id: '/practice-pos',
  path: '/practice-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminateRoute = TerminateRouteImport.update({
  id: '/terminate',
  path: '/terminate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaSignupRoute = ApiBetaSignupRouteImport.update({
  id: '/api/beta-signup',
  path: '/api/beta-signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/practice-pos': typeof PracticePosRoute
  '/privacy': typeof PrivacyRoute
  '/terminate': typeof TerminateRoute
  '/terms': typeof TermsRoute
  '/api/beta-signup': typeof ApiBetaSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/practice-pos': typeof PracticePosRoute
  '/privacy': typeof PrivacyRoute
  '/terminate': typeof TerminateRoute
  '/terms': typeof TermsRoute
  '/api/beta-signup': typeof ApiBetaSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/practice-pos': typeof PracticePosRoute
  '/privacy': typeof PrivacyRoute
  '/terminate': typeof TerminateRoute
  '/terms': typeof TermsRoute
  '/api/beta-signup': typeof ApiBetaSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/practice-pos'
    | '/privacy'
    | '/terminate'
    | '/terms'
    | '/api/beta-signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/practice-pos'
    | '/privacy'
    | '/terminate'
    | '/terms'
    | '/api/beta-signup'
  id:
    | '__root__'
    | '/'
    | '/beta'
    | '/practice-pos'
    | '/privacy'
    | '/terminate'
    | '/terms'
    | '/api/beta-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaRoute: typeof BetaRoute
  PracticePosRoute: typeof PracticePosRoute
  PrivacyRoute: typeof PrivacyRoute
  TerminateRoute: typeof TerminateRoute
  TermsRoute: typeof TermsRoute
  ApiBetaSignupRoute: typeof ApiBetaSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-pos': {
      id: '/practice-pos'
      path: '/practice-pos'
      fullPath: '/practice-pos'
      preLoaderRoute: typeof PracticePosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminate': {
      id: '/terminate'
      path: '/terminate'
      fullPath: '/terminate'
      preLoaderRoute: typeof TerminateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-signup': {
      id: '/api/beta-signup'
      path: '/api/beta-signup'
      fullPath: '/api/beta-signup'
      preLoaderRoute: typeof ApiBetaSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaRoute: BetaRoute,
  PracticePosRoute: PracticePosRoute,
  PrivacyRoute: PrivacyRoute,
  TerminateRoute: TerminateRoute,
  TermsRoute: TermsRoute,
  ApiBetaSignupRoute: ApiBetaSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
